# people-counter.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-counter
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: people-counter
  template:
    metadata:
      labels:
        app: people-counter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: people-counter
        image: moootid/people-counter:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: PORT
          value: "8000"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "myapp"
        - name: DB_PASSWORD
          value: "YOUR_DB_PASSWORD"  # TODO: Replace with your actual database password
        - name: DB_NAME
          value: "myapp"
        - name: AWS_DEFAULT_REGION
          value: "eu-central-1"
        - name: AWS_SECRET_ACCESS_KEY
          value: "YOUR_AWS_SECRET_ACCESS_KEY"  # TODO: Replace with your actual AWS secret access key
        - name: AWS_ACCESS_KEY_ID
          value: "YOUR_AWS_ACCESS_KEY_ID"  # TODO: Replace with your actual AWS access key ID
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: people-counter
  namespace: myapp
spec:
  selector:
    app: people-counter
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP