# video-transcoder.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-transcoder
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-transcoder
  template:
    metadata:
      labels:
        app: video-transcoder
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
    spec:
      containers:
      - name: video-transcoder
        image: moootid/video_transcoder:latest
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: PORT
          value: "4000"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: "myapp"
        - name: DATABASE_PASSWORD
          value: "YOUR_DB_PASSWORD"  # TODO: Replace with your actual database password
        - name: DATABASE_NAME
          value: "myapp"
        - name: TEMP_DIR
          value: "/tmp"
        - name: S3_BUCKET
          value: "YOUR_S3_BUCKET_NAME"  # TODO: Replace with your actual S3 bucket name
        - name: AWS_REGION
          value: "eu-central-1"
        - name: AWS_ACCESS_KEY_ID
          value: "YOUR_AWS_ACCESS_KEY_ID"  # TODO: Replace with your actual AWS access key ID
        - name: AWS_SECRET_ACCESS_KEY
          value: "YOUR_AWS_SECRET_ACCESS_KEY"  # TODO: Replace with your actual AWS secret access key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: video-transcoder
  namespace: myapp
spec:
  selector:
    app: video-transcoder
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP